Iteration 1 Whiteboard
cubixel/TutorPoint pull request #3
Opened 2020-03-03 18:04 UTC by ojhstill

### TP011 - Interactive Whiteboard
**User Stories Complete:** 016
**Authors:** Oliver Still and Cameron Smith

2020-03-03 18:34 UTC, ojhstill commented on client/src/main/java/application/Launcher.java
> +        viewFactory.showWhiteboardWindow();
Perhaps change back to `viewFactory.showLoginWindow()`.

2020-03-03 19:01 UTC, JADGardner requested changes
Everything looks good to me. Just need to remove the README from the pull request and fix that line in Launcher.java

2020-03-03 22:34 UTC, dmb537 requested changes
Looks good yeah - just the previously mentioned change (or rather, not change) to Launcher.java. Don't know how to do that though - might be able to be done during the merging process or something?

2020-03-03 22:41 UTC, ojhstill commented
All fixed - Should be good to go now!

2020-03-03 23:21 UTC, dmb537 approved these changes
Yeah looks good now

2020-03-03 23:22 UTC, dmb537 approved these changes

2020-03-04 07:28 UTC, JADGardner approved these changes
All good, approved! 👍

2020-03-04 07:29 UTC, merged